### PR TITLE
Update the keys in order to include SmartHub

### LINKED ISSUE #54: Key code for smart hub
I'm trying to use samsungctl to automate some common tasks. However, most tasks relevant to me involves the smart hub, and I can't find or figure out the key code for that. Does anyone know it, or is anyone able to figure it out by sniffing the network traffic?

### PR DESCRIPTION
**Pull request by pedrinho**
closes #54

### CODE REVIEW

**Comment by lervag** [comment]
Nice! I was just thinking of looking at this, and then you already did it. :)

**Comment by lervag** [comment]
Although, I would also add this:

```diff
diff --git samsungctl/interactive.py samsungctl/interactive.py
index d6c2e21..c882497 100644
--- samsungctl/interactive.py
+++ samsungctl/interactive.py
@@ -10,6 +10,7 @@ _mappings = [
     ["KEY_NPAGE",     "KEY_CHDOWN",        "Page Down", "P Down"],
     ["\n",            "KEY_ENTER",         "Enter",     "Enter"],
     ["KEY_BACKSPACE", "KEY_RETURN",        "Backspace", "Return"],
+    ["KEY_CONTENTS",  "KEY_RETURN",        "H",         "Smart Hub"],
     ["l",             "KEY_CH_LIST",       "L",         "Channel List"],
     ["m",             "KEY_MENU",          "M",         "Menu"],
     ["s",             "KEY_SOURCE",        "S",         "Source"],
```

That is, include the key to the `samsungctl/iteractive.py`.

**Comment by pedrinho** [comment]
Agreed. Will update the PR with this code

**Comment by Ape** [comment]
Thanks!

**Pull request merged**
