### PR TITLE
changed key_interval from 1sec to 0.5sec

### PR DESCRIPTION
**Pull request by StancuFlorin**
This is the solution for this issue: https://github.com/Ape/samsungctl/issues/40

### CODE REVIEW

**Comment by Ape** [comment]
The previous 1 second interval is probably way too long. I'm quite sure that I am going to merge is PR. However, since I am not using the websocket backend myself I would like to have somebody else test how this change behaves on their TV model and use case.

In addition, I would like to have more experiences about the correct interval value. Is 0.2 seconds too little? What is the safest choice here?

**Comment by eclair4151** [comment]
i have tested this an i have found that .25 seconds works fine on websockets. 1 second is way to long

**Comment by Ape** [comment]
Please make a pull request with 0.25 seconds and I will merge it. Or please say if you have further experiences about what would be the correct value.

**Comment by eclair4151** [comment]
after more testing i think half a second is better. when i made it 0.25 seconds i started to loose commands if i sent 10 in a row. but at 0.5 i never had an issue. i think you are prob fine to just merge this PR

**Comment by Ape** [comment]
Thanks. It's a bit difficult for me to handle websocket features because I cannot test them myself.

**Pull request merged**
